### ISSUE TITLE
relabel terminology consistency?

### ISSUE THREAD

**Issue by cburroughs** [joyent/triton-prometheus#1]
Right now the config is setting:

```
      - source_labels: [__meta_triton_machine_alias]
        target_label: instance
```

Don't we colloquial used "instance" to mean the instance id?  What should we then call `__meta_triton_machine_id`?

FWIW when I've used CMON in the past I've set:
```
    relabel_configs:
      - source_labels: [__meta_triton_machine_alias]
        target_label: alias
      - source_labels: [__meta_triton_machine_id]
        target_label: instance
```
